paths:
  data_dir: './datasets/penn'
  vggnet: './pretrained/vgg19.npy'
  log_dir: 'results/'

training:
  n_steps: 30000000
  summary_interval: 500
  test_interval: 500
  checkpoint_interval: 20000
  log_interval: 250
  batch_size: 16
  lr:
    start_val: 0.0001
    step: 20000
    decay: 0.95

model:
  n_pts: 40
  n_action: 9
  cell_info: [1024, 1024]
  vae_dim: 64