name: penn-40pts

training:
  dset: penn
  datadir: /dataset/data/datasets/penn
  n_summary: 500
  n_test: 500
  n_checkpoint: 20000
  batch_size: 16
  n_action: 9
  cell_info: [1024, 1024]
  vae_dim: 64
  log_dir: '/results/penn-40pts'
  checkpoint_fname: ''
  lr:
    start_val: 0.0001
    step: 20000
    decay: 0.95

model:
  n_maps: 40
  gauss_std: 0.07
  render_input_sz: 32
  n_filters: 32
  renderer_stride: 2
  min_res: 16
