name: penn-40pts

training:
  dset: penn
  train_dset_params:
    subset: train
  test_dset_params:
    subset: test
    order_stream: True
    max_samples: 1000
  datadir: /dataset/data/datasets/penn
  lr:
    start_val: 0.0001
    step: 20000
    decay: 0.95

model:
  n_maps: 40
  gauss_std: 0.07
  render_input_sz: 32
  n_filters: 32
  renderer_stride: 2
  min_res: 16
